pipeline {
    agent any

    environment {
        IMAGE_NAME = "devops-cicd-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/YOUR_USERNAME/Devops-6th-Sem.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Push Image') {
            steps {
                echo "Simulating Docker Hub Push"
            }
        }

        stage('Deploy with Helm') {
            steps {
                sh 'helm upgrade --install myapp ./helm-chart'
            }
        }
    }

    post {
        success {
            echo '✅ CI/CD Pipeline Completed Successfully'
        }

        failure {
            echo '❌ Pipeline Failed'
        }
    }
}
