apiVersion: v1
kind: Service
metadata:
  name: devops-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: devops-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30010
